#!/bin/sh

local=/home/keyboardcat/Documents/MineRTC/

cd $local || exit
./gradlew build
scp build/libs/MineRTC-1.0-SNAPSHOT.jar 192.168.68.112:/home/keyboardcat/mc_servers/IntpMCServer/plugins/
ssh 192.168.68.112 "tmux send -t mc 'stop' Enter"
sleep 5
ssh 192.168.68.112 "tmux send -t mc 'sudo java -jar paper-1.19.4-471.jar -nogui' Enter"




