name: MineRTC
version: 0.1a0
api-version: '1.19'
main: io.github.keyboardcat1.minertc.MineRTC
description: The easiest proximity chat plugin to use
commands:
  connect:
    description: Creates link to connect to
    usage: /connect
libraries:
  - org.eclipse.jetty:jetty-server:11.0.14
  - org.eclipse.jetty.websocket:websocket-jetty-server:11.0.14
  - org.eclipse.jetty.websocket:websocket-jetty-api:11.0.14